# Generated by Django 4.0.1 on 2022-02-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auction_listing_bids_commwnr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commwnr',
            new_name='Commwns',
        ),
    ]
