# Generated by Django 4.0.1 on 2022-02-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_rename_commwnr_commwns'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commwns',
            new_name='Comments',
        ),
    ]
